### ISSUE TITLE
IDEA / Mendix form builder for Studio

### ISSUE THREAD

**Issue by Grasshooper** [mendix/WorkflowCommons#1]
Hi MX Team,

I was using the form builder while configuring the approval app from mendix studio, and found it very useful and luckily one of my client need the same functionality in their mendix app . That is they want to incorporate a form builder inside the app.
Is it possible to do that ? can you please provide me any lead on how to achieve this functionality that just like in Approval app form builder you can edit the Label and an attribute is created in the Entity level.

Any lead will be much helpful

TIA
GJ

**Comment by JefHellemansMendix** [comment]
Hi @Grasshooper,

If you are talking about [this template](https://new.mendix.com/link/templates/117472), which then redirects to Studio and allows you to build a new app using those forms, that is a custom flow built in Studio. Studio works on top of our [Mendix SDK](https://docs.mendix.com/apidocs-mxsdk/mxsdk/) and that's where you should look to build similar functionality, although I imagine hooking this into a Mendix app that then changes itself is not an easy thing to do.

Best of luck!

Kind regards,
Jef Hellemans
