### ISSUE TITLE
When aborting a workflow, snippet "Snip_DashboardContext_Timeline" doesn't work anymore

### ISSUE THREAD

**Issue by tanerg** [mendix/WorkflowCommons#3]
When you abort a workflow the microflow "DS_WorkflowTask_AssignedToUser" used by snippet "Snip_DashboardContext_Timeline" returns also aborted user task which the user hasn't access to due to defined Xpath constraints. I fixed this for our project by setting the apply entity access for the microflow in question.

**Comment by MitchelMx** [comment]
Hello Tanerg,

Thank you for submitting your bug, we will look into this and apply a fix in an upcoming version of the module.

**Comment by MitchelMx** [comment]
Hello Tanerg,

This issue has been resolved and a fix for it will be released with the upcoming 1.3.0 version which in turn will be released right after Mx 9.6 will be released due to a dependency on that version.
