### ISSUE TITLE
Missing associations in system module

### ISSUE THREAD

**Issue by HenkBiertank** [mendix/WorkflowCommons#37]
In Mendix 10.0.0 beta 1, when I download workflow commons 3.1.0 in a fresh project you'll get the error: The selected association 'System.WorkflowUsrTask_Assigneees' no longer exists.

![afbeelding](https://github.com/mendix/WorkflowCommons/assets/49210634/8ae43964-c0f0-492c-8774-9c15df94c84f)

**Comment by allard-mx** [comment]
Hi Henk,

Thank you for reaching out, and sorry for the (very) late reply. Starting with Mendix 10.0.0-beta2, assignees are now a reference set. Please see the [release notes](https://github.com/mendix/WorkflowCommons/releases/tag/3.0.0) of version 3.0.0 for more information.
