### ISSUE TITLE
Retrieve Issue - Postgres Sql ' could not determine data type of parameter' 

### ISSUE THREAD

**Issue by h4wk0** [mendix/WorkflowCommons#47]
**ISSUE**
When running v3.3.1 in Mendix version 10.8.1 there is an issue which occurs when attempting to view the issue is caused when attempting to view the page WorkflowCommons.Workflow_Dashboard while running in Mendix Cloud.

**TO REPRODUCE**
1. Create a new project in Mendix 10.8.1 (this seems to affect more recent versions also, but not 10.6.1)
2. Install and configure the Workflow Comunity Commons module. (Add the workflow admin centre to the navigation) 
3. Deploy the app to a free app/sandbox instance in mendix cloud
4. Login and attempt to access the Workflow Dashboard - an error will occur and no data will populate the page. 
**Note:** this issue is not reproduceable when running locally. 

**ROOT CAUSE ANALISYS**
After setting error handling on the retrieve activity the specific error message I get is "ERROR: could not determine data type of parameter $2"

I've traced the cause of the error to the retrieve activities that occur in the following microflows: 
- SUB_Workflow_CountCompletedOverdue
- SUB_Workflow_CountCompletedOnTime
- SUB_Workflow_AverageHandlingTime
- SUB_Workflow_CountInProgress
- SUB_Workflow_CountCompleted
- SUB_Workflow_CountOverdue

Specifically, the xpaths used in the retrieve activities seems to be the cause of the issue. 

**WORK AROUND**
I was able to resolve the issue by removing xpath constraints from the retrieve, then adding a list operation - filter by expressing, into which I inserted and amended the xpath constraint. After repeating this process on the 6 aforementioned microflows. The issue was resolved.

**Comment by allard-mx** [comment]
Thank you for reporting this issue. We've looked into it and reported this internally. To ensure you can still use Workflow Commons, we included a fix in the latest [marketplace release](https://marketplace.mendix.com/link/component/117066) (v3.4.0). 

Thanks again!
